let pairs = [
	['1-a.png', '1-b.png'],
	['1-a-flip-color.png', '1-b-flip-color.png'],
	['1-a-rotated.png', '1-b-rotated.png'],
	['2-a.png', '2-b.png'],
	['2-a-flip-color.png', '2-b-flip-color.png'],
	['2-a-rotated.png', '2-b-rotated.png'],
	['3-a.png', '3-b.png'],
	['3-a-flip-color.png', '3-b-flip-color.png'],
	['3-a-rotated.png', '3-b-rotated.png'],
	['4-a.png', '4-b.png'],
	['4-a-flip-color.png', '4-b-flip-color.png'],
	['4-a-rotated.png', '4-b-rotated.png'],
	['5-a.png', '5-b.png'],
	['5-a-flip-color.png', '5-b-flip-color.png'],
	['5-a-rotated.png', '5-b-rotated.png'],
	['6-a.png', '6-b.png'],
	['6-a-flip-color.png', '6-b-flip-color.png'],
	['6-a-rotated.png', '6-b-rotated.png'],
	['7-a.png', '7-b.png'],
	['7-a-flip-color.png', '7-b-flip-color.png'],
	['7-a-rotated.png', '7-b-rotated.png'],
	['8-a.png', '8-b.png'],
	['8-a-flip-color.png', '8-b-flip-color.png'],
	['8-a-rotated.png', '8-b-rotated.png'],
	['9-a.png', '9-b.png'],
	['9-a-flip-color.png', '9-b-flip-color.png'],
	['9-a-rotated.png', '9-b-rotated.png'],
	['10-a.png', '10-b.png'],
	['10-a-flip-color.png', '10-b-flip-color.png'],
	['10-a-rotated.png', '10-b-rotated.png'],
	['11-a.png', '11-b.png'],
	['11-a-flip-color.png', '11-b-flip-color.png'],
	['11-a-rotated.png', '11-b-rotated.png'],
	['12-a.png', '12-b.png'],
	['12-a-flip-color.png', '12-b-flip-color.png'],
	['12-a-rotated.png', '12-b-rotated.png'],
	['13-a.png', '13-b.png'],
	['13-a-flip-color.png', '13-b-flip-color.png'],
	['13-a-rotated.png', '13-b-rotated.png']
];

export { pairs };
